### ISSUE TITLE
Help me regarding convertion of Bitmap to jpg photo

### ISSUE THREAD

**Issue by Jayakrishna112** [adafruit/Adafruit_CircuitPython_OV7670#20]
I have initialized the camera(OV7670) and captured and stored it into a Bitmap. I need a help to change it to jpg format.

**Comment by FoamyGuy** [comment]
I believe it's not currently possible to easily convert from a Bitmap to jpg format. Recently the ability to decode jpgs was added as a core module: https://docs.circuitpython.org/en/latest/shared-bindings/jpegio/index.html but this currently supports decoding only, not encoding.

**Comment by Jayakrishna112** [comment]
Ok.
Is there any way to convert it .bmp file and save.
